# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  flags:
      # try to prevent paths from local system from leaking into build
      - -trimpath
  ldflags:
      # this is the default without the date being set. The date would
      # prevent build reproducibility
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.builtBy=goreleaser
  goos:
    - linux
    - darwin
    - openbsd
    - freebsd
    - netbsd
    - dragonfly
    - windows
    - solaris
    - illumos
  goarch:
    - amd64
    - arm
    - arm64
  goarm:
    - 6
    - 7
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
